/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import project.Function.ProgramLogic;
import project.Model.ModelProgram;

/**
 *
 * @author Abner
 */
public class MainFrame extends javax.swing.JFrame {

    ProgramLogic logic = new ProgramLogic();
    ArrayList list = new ArrayList();
    
    public MainFrame() {
        initComponents();
        ta_result.setText(logic.label);
        rb_laki.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rb_laki = new javax.swing.JRadioButton();
        rb_perempuan = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cb_health = new javax.swing.JComboBox<>();
        btn_proses = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_result = new javax.swing.JTextArea();
        dp_umur = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Deteksi Dini Penyakit Corona");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(85, 30, 609, 55);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 121, 162, 43);

        tf_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(tf_name);
        tf_name.setBounds(240, 122, 454, 43);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jenis Kelamin");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 183, 162, 44);

        rb_laki.setText("Laki");
        rb_laki.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(rb_laki);
        rb_laki.setBounds(240, 197, 115, 23);

        rb_perempuan.setText("Perempuan");
        jPanel1.add(rb_perempuan);
        rb_perempuan.setBounds(447, 197, 115, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Health");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 330, 162, 55);

        cb_health.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH GEJALA YANG ANDA RASAKAN-", "Demam >38C, Batuk, Nafas Taknormal/Sesak, Dahak Kental, Lemas, Sinar X", "Demam, Batuk, Hidung Meler, Bersin, Muntah, Diare, Otot Nyeri", "Batuk, Hidung Tersumbat, Bersin, Radang", "Merasakan gejala lain yang tidak tertera di atas" }));
        cb_health.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cb_health.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_healthActionPerformed(evt);
            }
        });
        jPanel1.add(cb_health);
        cb_health.setBounds(240, 333, 454, 55);

        btn_proses.setText("Proses");
        btn_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesActionPerformed(evt);
            }
        });
        jPanel1.add(btn_proses);
        btn_proses.setBounds(240, 588, 454, 38);

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_clear);
        btn_clear.setBounds(240, 394, 454, 23);

        btn_exit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon("E:\\Tugas\\formlogin\\src\\formlogin\\images\\close.png")); // NOI18N
        btn_exit.setBorder(null);
        btn_exit.setBorderPainted(false);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_exitMouseReleased(evt);
            }
        });
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit);
        btn_exit.setBounds(750, 0, 60, 60);

        ta_result.setColumns(20);
        ta_result.setRows(5);
        jScrollPane1.setViewportView(ta_result);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(240, 431, 454, 151);

        dp_umur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dp_umurActionPerformed(evt);
            }
        });
        jPanel1.add(dp_umur);
        dp_umur.setBounds(240, 233, 454, 66);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tanggal Lahir");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 235, 162, 57);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abner\\Downloads\\logo-who-png-3.png")); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 80, 350, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dp_umurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dp_umurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dp_umurActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        ta_result.setText("Anda Telah Menghapus Hasil Program"
            + ", Tolong Masukan Data Anda Kembali!");
        tf_name.setText("");
        list.clear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesActionPerformed
        // TODO add your handling code here:
        String name = tf_name.getText();
        String gender = rb_laki.getText();
        String health = cb_health.getSelectedItem().toString();
        Date date = dp_umur.getDate();
        Date now = new Date();
        int age = now.getYear()- date.getYear();

        ModelProgram mp = new ModelProgram();
        mp.setName(name);

        String result = logic.result(health, gender, mp);
        if (tf_name.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "Tolong isi nama anda."
                , "Messege", HEIGHT);
            ta_result.setText("Coba Lagi");
        }

        else if (cb_health.getSelectedIndex() ==0){
            JOptionPane.showMessageDialog(rootPane, "Tolong isi keluhan anda"
                , "Messege", HEIGHT);
            ta_result.setText("Coba Lagi");
        }

        else if (age <= 24 && rb_laki.isSelected()){
            ta_result.setText(result + " , Tolong Isolasi Diri Anda Di Rumah."
                + "\nKasus positif corona pada lelaki di Indonesia sebesar 71%");
        }

        else if (age > 24 && rb_laki.isSelected()){
            ta_result.setText(result + " , Silahkan ke rumah sakit terdekat"
                + " untuk pemeriksaan lebih lanjut." + "\nKasus positif corona pada"
                + "lelaki di Indonesia sebesar 71%");
        }

        else if (age <= 24 && rb_perempuan.isSelected()){
            ta_result.setText(result + " , Tolong Isolasi Diri Anda Di Rumah"
                + "\nKasus positif corona pada perempuan di Indonesia sebesar 29%");
        }

        else if (age > 24 && rb_perempuan.isSelected()){
            ta_result.setText(result + " , Silahkan ke rumah sakit terdekat"
                + " untuk pemeriksaan lebih lanjut." + "\nKasus positif corona pada"
                + " perempuan di Indonesia sebesar 29%");
        }

        if(!(name.matches("[a-zA-Z0-9]+"))){
            JOptionPane.showMessageDialog(rootPane, "Tolong masukan nama anda "
                + "dengan Alphanumeric saja.", "Messege", HEIGHT);
            tf_name.setText("");
            ta_result.setText("Coba Lagi");
        }
    }//GEN-LAST:event_btn_prosesActionPerformed

    private void cb_healthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_healthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_healthActionPerformed

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
       this.dispose();
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        
    }//GEN-LAST:event_btn_exitMouseEntered

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
       
    }//GEN-LAST:event_btn_exitMouseExited

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
       
    }//GEN-LAST:event_btn_exitMousePressed

    private void btn_exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseReleased
        
    }//GEN-LAST:event_btn_exitMouseReleased

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
      
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
    }//GEN-LAST:event_jPanel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_proses;
    private javax.swing.JComboBox<String> cb_health;
    private org.jdesktop.swingx.JXDatePicker dp_umur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_laki;
    private javax.swing.JRadioButton rb_perempuan;
    private javax.swing.JTextArea ta_result;
    private javax.swing.JTextField tf_name;
    // End of variables declaration//GEN-END:variables
}
